name: build-native-apps
on:
    push:
        tags:
            # Build on every tag in the form v1.2.3-something.4
            - 'v*'
jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2.3.1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}

                  build_script_name: build:electron

                  release: true
